server:
  port: 8081

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:

        - id: auth-service
          uri: lb://auth-service
          predicates:
            - Path=/api/v1/auth/**

        - id: api-registry-service
          uri: lb://api-registry-service
          predicates:
            - Path=/api/v1/apis/**

        - id: subscription-service
          uri: lb://subscription-service
          predicates:
            - Path=/api/v1/subscriptions/**

        - id: analytics-service
          uri: lb://analytics-service
          predicates:
            - Path=/api/v1/analytics/**
eureka:
  client:
    service-url:
      defaultZone: http://discovery-server:8761/eureka
  instance:
    prefer-ip-address: true
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    prometheus:
      enabled: true